# Written by the Backstage Database template.
apiVersion: platform.jordandesigns.io/v1alpha1
kind: Database
metadata:
  name: orders-az
  namespace: team-ops
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        platform.jordandesigns.io/cloud: azure
  size: small
  region: us-east
  owner: guest
  costCenter: cc-1001
  environment: dev
