# Live proof of the task definition fix (ADR-0022, 2026-10-03), written by hand from the WebService template output.
apiVersion: platform.jordandesigns.io/v1alpha1
kind: WebService
metadata:
  name: web-tdfix
  namespace: team-demo
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        platform.jordandesigns.io/cloud: aws
  image: public.ecr.aws/nginx/nginx-unprivileged@sha256:18d5312e3b7e455cf9e4fb8becfc2dafaf98063dab542759c2a38708956574b7
  port: 8080
  healthPath: /
  size: small
  visibility: public
  maxInstances: 1
  region: us-east
  owner: jordann6
  costCenter: cc-1001
  environment: dev
