# Live proof of the task definition fix (ADR-0022, 2026-10-03), written by hand from the WebService template output.
apiVersion: platform.jordandesigns.io/v1alpha1
kind: WebService
metadata:
  name: web-tdfix2
  namespace: team-demo
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        platform.jordandesigns.io/cloud: aws
  image: public.ecr.aws/nginx/nginx-unprivileged@sha256:59678856b05324b7f6371f26eb1520be7fcd8bdc8ab380fc4913db8503e5a842
  port: 8080
  healthPath: /
  size: small
  visibility: public
  maxInstances: 1
  region: us-east
  owner: jordann6
  costCenter: cc-1001
  environment: dev
