# Live proof of the task definition fix (ADR-0022, 2026-10-03), written by hand from the WebService template output.
apiVersion: platform.jordandesigns.io/v1alpha1
kind: WebService
metadata:
  name: web-tdfix2
  namespace: team-demo
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        platform.jordandesigns.io/cloud: aws
  image: public.ecr.aws/nginx/nginx-unprivileged@sha256:f9dfa9c20b2b0b7c5cc830374f22f23dee3f750b6c5291ca7e0330b5c88e6403
  port: 8080
  healthPath: /
  size: small
  visibility: public
  maxInstances: 1
  region: us-east
  owner: jordann6
  costCenter: cc-1001
  environment: dev
