# Written by the Backstage Database template.
apiVersion: platform.jordandesigns.io/v1alpha1
kind: Database
metadata:
  name: orders-gcp
  namespace: team-data
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        platform.jordandesigns.io/cloud: gcp
  size: small
  region: us-east
  owner: guest
  costCenter: cc-1001
  environment: dev
