# Written by the Backstage WebService template.
apiVersion: platform.jordandesigns.io/v1alpha1
kind: WebService
metadata:
  name: web-gcp-a
  namespace: team-data
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        platform.jordandesigns.io/cloud: gcp
  image: public.ecr.aws/nginx/nginx-unprivileged@sha256:59678856b05324b7f6371f26eb1520be7fcd8bdc8ab380fc4913db8503e5a842
  port: 8080
  healthPath: /
  size: small
  visibility: public
  maxInstances: 1
  region: us-east
  owner: guest
  costCenter: cc-1001
  environment: dev
